//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processing
    {
        public int idOrder { get; set; }
        public string Datemovement { get; set; }
        public int idClient { get; set; }
        public string typemovement { get; set; }
        public string keys { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual order order { get; set; }
    }
}
